### ISSUE TITLE
constant summary of public health data

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/PHES-ODM#111]
When summarizing line list health data that can look like this (Note this is fake generated data)

![image](https://user-images.githubusercontent.com/19482839/109854329-ebb35f00-7c24-11eb-8037-31e8e5bf5529.png)

there are several ways to summarize this data for inclusion in the DB which from the start is not supposed to have individual level information in it.

you could 
 * ignore `NA` for `postal_code` and `*_dates`
 * Ignore `NA` for `postal_code` and estimate values for `*_dates` from other dates

I think the best thing to do would be the second but it means you would have estimated dates mixed in with recorded dates in the same record, with no indication that some of the dates were estimated or how they were estimated. 

conversely if you ignore `NA` for both it creates a problem of underestimating counts on a given day and even bigger problems  if there is bias in the `NA` distribution over time, which there normally is.

I am not sure how to solve this with the current structure, other then to say add a column to the `CovidPublicHealthData` table called `nDateEst` and `dateEstMethod`

**Comment by mathew-thomson** [comment]
It seems to me that this issue is closely related to issue #35 - it seemed to me there that line level case data couldn't be something that we'd want to add. Is this something to revisit, @DougManuel ? 

If we do, I think that it could actually be quite simple to add, we can record each line as an individual measure in a `compartment = person` and each person is also their own sample with a single measure. Something to discuss further, maybe.

**Comment by mathew-thomson** [comment]
In line with issue #35 I'm closing this issue since we wont be recording line-level case data. We also won't be the ones transforming this data into summary statistics (generally). I think that I agree with Howard that the second approach is the stronger of the two options (Ignore NA for postal_code and estimate values for *_dates from other dates) but this is something to only revisit if we begine needing to aggregate line-level case data ouselves.
