### ISSUE TITLE
Archived samples

### ISSUE THREAD

**Issue by jeandavidt** [Big-Life-Lab/PHES-ODM#119]
We have labs in Québec that are starting to either prepare samples for long-term storage or are going through their archive of test samples. 

Since the collection of COVID samples will likely only occur in the next few years, but analysis can go on for much longer, and since storage conditions might affect the analysis results, it might be worth including long-term storage info in the data model.

The researcher working on this right now in Trois-Rivières is suggesting the following info:
1) Whether a sample has been archived; 
2) What form the stored sample is in (filter, rna, raw wasterwater, pellet, ...); 
3) Where it is archived (lab);
4) How it is stored (i.e., temperature)

The way I see it, this info would probably be best placed in a new table, as storage conditions for a given sample may change over time. There may also be a need to add whether the ww measurement was performed on archived or fresh samples

Looking forward to a discussion on this :)

**Comment by mathew-thomson** [comment]
It seems like this could be quite messy if we tried to add it to version 2, and may be out of scope. May be best to look at for version 2.1 or version 3. Part of this "archived" structure seems like it would be doing the work of a lab's management system by tracking where samples are, and further - if no measures or methods are applied to a sample, why are we even recording it in the ERD? But if that sample later gets de-archived and analyzed, it would be helpful to know more about it's history. Some of that could already be captured by the collection date and analysis date being so far apart. Storage temp, etc. would also provide some level of detail. But it may be worth considering how we track the "lifecourse" of such an archived sample, even if this turns out to be a relatively rare event.

What say you, @DougManuel ?

**Comment by mathew-thomson** [comment]
Continuing with the line of thinking that archiving in kind of out of scope for the ODM, the data on when a sample was collected and when it was analyzed are available, along with some information about how it was stored. This serves a little more detail on what we'd want to know about archived samples - I've also made a measureID for storage time in case we want to be even more explicit about this.
