### ISSUE TITLE
Add municipality to site table

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/PHES-ODM#121]
Add municipality to site table, as suggested by Ric Mucciacciaro

**Comment by hswerdfe** [comment]
add country state province/state field also ???

**Comment by NielsNicolai** [comment]
In the CDC WBE template they also include the **zipcode**. Might be useful for us too.

**Comment by jeandavidt** [comment]
I suggest we add all relevant address fields:
* Civic number
* Street
* City
* Municipality
* Province/State
* Country
* Postal Code
* (maybe) something like 'onSiteLocation` for people to explain *where* inside the site they are actually sampling

I don't think there would be any downsides, no?

**OR**

Since we are storing info about labs and people too (and those have addresses as well), maybe we make an Address table with all those fields, and we link `Lab`, `Site`and `Reporter`to it using `addressID`?

**Comment by yulric** [comment]
> @DougManuel @yulric @GauriSaran
> I suggest we add all relevant address fields:
> 
> * Civic number
> * Street
> * City
> * Municipality
> * Province/State
> * Country
> * Postal Code
> * (maybe) something like 'onSiteLocation` for people to explain _where_ inside the site they are actually sampling
> 
> I don't think there would be any downsides, no?
> 
> **OR**
> 
> Since we are storing info about labs and people too (and those have addresses as well), maybe we make an Address table with all those fields, and we link `Lab`, `Site`and `Reporter`to it using `addressID`?

An address table is a better future proof solution, so your second option.

**Comment by NielsNicolai** [comment]
I would also go for having a separate address table. This will also avoid ending up with a lot of redundant addresses.

**Comment by mathew-thomson** [comment]
As per conversation here, the current structure for version 2 features a separate address table which captures the following fields:
- addressID
- addressLine1
- addressLine2
- city
- stateProvRegion
- zipPostalCode
- country
