### ISSUE TITLE
Include design capacity WWTP

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/PHES-ODM#123]
Currently, the only way to compare WWTP size is by comparing the population size that is being served (stored in the polygon table). This does however not necessarily translate linearly to the size of the WWTP. A better measure would be the capacity for which the WWTP was designed, expressed in `PE` in Europe and `MGD` in North-America. Let's include it to the `Site` table.

**Comment by mathew-thomson** [comment]
In today's meeting it sounds to me like we want to include design capacity as an attribute of a site within the site table. I think that based on this thread, plus the discussion in-meeting this morning, we can add a new field (an attribute) within the site table called "designCapacity". 

It seemed as though we wanted to list 'design capacity' as 'population equivalents' (PE), so it would make sense to have an attribute called 'design capacity', and then prescribe the units either as PE or  MGD (millions of gallons per day). However, within the current structure of the ODM, attributes don't have units. So I wonder: do we make design capacity a measure so that it can have these units? Or do we mandate specific units for the attribute of design capacity by calling it population equivalents? Or have I misunderstood out management of the population issue #215? My hunch is that these are separate but parallel issues. 

@jeandavidt @DougManuel @sorinsion - for your comment and consideration

**Comment by mathew-thomson** [comment]
After today's meeting it seems to me that folks are in agreement that design capacity should be a measurement, and not a site attribute. It has been added as a measure with `MGD` and `PE` (population equivalent) as units in the dictionary currently. Closing this issue for now.

**Comment by mathew-thomson** [comment]
As an addendum to this point, a measureSetReportID was added to the Site table to allow for more clearly lines of connection between a site and site measures. We are also adding potential groups and classes to specify out more site-specific measures and methods.
