### ISSUE TITLE
Weather and environmental variables

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#124]
Do we need additional weather and environmental variables other than the current measures (siteFlow, etc.)?

In Ottawa, there is a recent low signal which is corresponding to very active snowmelt. We are analyzing data on temperature and sewage conductivity, as a metric to reflect salinity. Ottawa uses a lot of salt for snow clearance on roads during the winter, with salt entering wastewater during the spring melt.

**Comment by davidchampredon** [comment]
Thinking out loud, I'm definitely not a specialist. 

- For WWTP we usually have metadata on the wastewater flows, TSS, temperature, etc. Maybe that's really what we need and what matters when considering RNA concentration at that sampling site. For example, if there's snowmelt close to a large city on day `d` but only appears on day `d+2` at the sampling site (sounds not realistic, just an example!), it seems more relevant (??) for interpreting the variation of RNA concentration to know that we have an increased volume on day `d+2`, as would probably indicate the flow readings from the WWTP.
- That being said, having an idea of notable environmental events is probably very helpful for the interpretation of the RNA concentration time series...
- I guess environmental data can easily become very large, even when considering just the basics (rainfall, temp, etc.). Do we really want to append a potentially voluminous dataset? Maybe having a script that "joins" on-demand the wastewater database with publicly available environmental databases (for example from [Weather Canada](https://climate.weather.gc.ca/historical_data/search_historic_data_e.html)) would be more manageable?

**Comment by NielsNicolai** [comment]
Currently the data model supports the following `SiteMeasures` that might be useful to correlate/quantify dilution due to snowmelt:

- envTemp | Environmental temperature
- envSnwD | Total depth of snow on the ground
- wwFlow | Flow of wastewater
- wTwemp | Temperature of the wastewater
- wwTSS | Total suspended solids concentration of the wastewater
- wwCond | Conductivity of the wastewater 

Any other variables that might be interesting looking at?

**Comment by NielsNicolai** [comment]
Hi @davidchampredon 
Note that because of the nature of most WW samples (daily grabs, or 24h composite samples). We will mostly use aggregated _daily averages_ for environmental data such as rain and temperature. Which makes that the amount of data is manageable within the data model. 

But I agree that once you need more granular data you might want to directly scrape that information from a weather service provider's website.

**Comment by DougManuel** [comment]
There seem to be two potential types of environmental data. 
1) Measures of the wastewater. 
1) Measures of the surrounding municipality. These measures seem similar to PHU data where they originate from partners and could be at a frequency (i.e. daily) that is different from measures taken directly from wastewater, including viral signal.

**Comment by mathew-thomson** [comment]
While still maintaining measures for envTemp, envSnwD, wwFlow, wwTemp, wwTSS, and wwCond (as mentioned in an above comment), we've now also added a weather measure (mostly for site) that captures more qualitative weather attributes (ie: Sunny, Rainy, Cloudy, Foggy, snowy). This is in line with the request outlined by EU DEEP (captured in issue #204)
