### ISSUE TITLE
Wide table format - consist approach

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#128]
Improvements in the documentation for wide tables are required for consistent use. 

- provide more examples. 
- formulas for calculating derived measures such as geometric means.

**Comment by DougManuel** [comment]
Discussion at today's working group with @vipileggi @NielsNicolai @jeandavidt @Cryofrog and others:
- include table name for all wide table variables. **Incorporate short table names.**
- continue to use underscore.

**Comment by jeandavidt** [comment]
Should the units also be part of the column names? When I automatically parse long table to create long tables, sometimes different rows that record the same parameter should not be directly aggregated together because they have different units.
For example, `SiteMeasure_wwflow_m3-d_single_value` and `SiteMeasure_wwflow_m3-h_single_value` have to be distinguished otherwise we would end up with nonsensical values.

**Comment by mathew-thomson** [comment]
This has been well fleshed out, and the wide-names table was added for version 2.2.

For additional details see: https://docs.phes-odm.org/wide-names.html
