### ISSUE TITLE
Outbreak occurring or under investigation

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#203]
Small area testing, such as a school, workplace, or long-term care home may have clinical cases reported or under investigation, but they are unable or do not have information about specific case counts. 

A boolean flag for outbreak could be used in these situations.

**Comment by mathew-thomson** [comment]
It seems extreme to have outbreak as an attribute of a measure, because it would be blank/no most of the time. And while I think it could work as an attribute of a site (updated semi-regularly), I think that in that table it's too far for the measure to be useful. I know we talked about this before, but I can't seem to find my notes. Do we think it makes sense to have outbreak be a boolean measure? With the instructions specifying that it means that related case counts may be approximate/incomplete? @DougManuel @jeandavidt - what do you think? Does this match what was discussed?

**Comment by jeandavidt** [comment]
I think `outbreakStart` and `outbreakEnd` could be site and population measures

**Comment by mathew-thomson** [comment]
I think that's smart! Could you say more about your rationale for having start and end measures instead of a singular boolean measure?

**Comment by jeandavidt** [comment]
To me, an outbreak is the span of time during which the cases "flare up" in a location, so I would want to record the entire period in which that flare up occurs. And I just figured that if we don't record the end of an outbreak explicitly, then we would have to create a new entry in measureReport on every single day of the outbreak. That would work too, but it might lead to more ambiguity - what happens if someone forgets to report that the outbreak is still ongoing on one of the days? By having a distinct measure for the beginning and the end, it would become obvious when an outbreak report is malformed (i.e., if it has a beginning and no end, or an end and no beginning)

**Comment by DougManuel** [comment]
I know teams that have an outbreak measure in their reports and data. I suggest that we include this measure. 

The concept of `outbreakStart` and `outbreakEnd` is very much part of public health practice and has important meaning and practice implications. For this reason, I don't worry too much about ambiguity, but there are reporting concerns. 

For version 2, I suggest that we include, but try to keep straightforward. I was wondering, for example, whether we want to have an outbreak ID (public health departments identify all give outbreaks an ID), but that and other concepts can be for a later version if there are requests.

**Comment by DougManuel** [comment]
What about having `outbreak` a measure. The values for the measure can be 'start', 'ongoing', and 'end'. Remember, each measure will have at least one `date` attribute. 

We can suggest the use of 'notes' to record outbreak ID and other information.

**Comment by mathew-thomson** [comment]
That seems reasonable to me, we'll just need to add like a `progressionCatSet` with the `start`, `on-going`, and `end` values. And then capture the other aspects with documentation. Let me know if we're all good with this and I'll make the additions to the dictionary and close this issue.

**Comment by DougManuel** [comment]
Makes sense. I think `outbreakCat` aligns better with the naming approach for category labels - but I'll leave it to you.

**Comment by mathew-thomson** [comment]
As outlined above, we now have an `outbreak` measureID with the valid categories set to `Outbreak start`, `Outbreak End`, and `Outbreak On-going` to capture this information. Details in the instructions column indicate that this means that the numbers reported at the time of outbreak are to be treated with some caution.

</body></html></div>
