### ISSUE TITLE
valueFlag results quality indicators

### ISSUE THREAD

**Issue by vipileggi** [Big-Life-Lab/PHES-ODM#209]
Further to our discussion this morning on the 'valueFlag' values. The Ontario Labs that participate in our Wastewater Surveillance Initiative use data quality indicators (e.g., ND, UJ, J see link to referenced 'Protocol'; see pages x, 31 and 32 for definitions). Also included an image of a typical Excel table using this approach.

[https://www.researchgate.net/publication/354248379_Protocol_for_Evaluations_of_RT-qPCR_Performance_Characteristics_Technical_Guidance](url)

![image](https://user-images.githubusercontent.com/74632605/145871219-3885691e-695d-4b47-88d9-6a4f1545c701.png)

**Comment by mathew-thomson** [comment]
To address this issue, and issue #210 and #130  - we are going to create "quality flag sets". These will be associated with measures and sames, and have different quality flags associated with the sets, as appropriate. 

For example - right now were are thinking there would be a sample quality set, with flags for leaked sample, improper storage temp, etc. as per issue #130 . There would be a PCR quality set that captures the levels mentioned here that are currently used by MECP, namely: B, FI, AI, ND, J, and UJ, with an additional value for 'no concerns'. Then there would be a generic quality set, with values for 'no quality concerns', and 'quality concerns not-otherwise defined'. 

This way we partially avoid breaking changes from version 1, and incorporate the current use by MECP moving forward.

Do folks have feedback on this proposal, or any issues? @vipileggi @Bahamyirou in particular.

**Comment by vipileggi** [comment]
@mathew-thomson no issues and thanks for addressing this issue.

**Comment by mathew-thomson** [comment]
Fantastic - closing this issue now.
