### ISSUE TITLE
max/min value

### ISSUE THREAD

**Issue by mathew-thomson** [Big-Life-Lab/PHES-ODM#222]
In the parts list we are specifying a max and min value, and have a column for each of these points.  There seems to need to be some clarification on their application, however. Are these only necessary to populate for measures? Or should they be applied to units? Or both? 

Furthermore, is their function to:
1. specify the minimum and maximum number of characters, or the smallest and largest value.
2. specify what makes physical sense for a measure (i.e. temperature can be between absolute zero and absolute hot; pH can be between 1 and 14) or,
3. specify what makes sense for a given measure/unit (i.e no temperature will be close to absolute zero or absolute hot, so should it be bounded within -60 to +60 Celcius, for example). My only concern on this point is that I don't know, necessarily, what the bounds of what makes sense for every measure. Making inputting this logical limits somewhat challenging. 

Looking forward to hearing input on this, @sorinsion @jeandavidt @DougManuel 

(tangentially related to issues #128 and #174 )

**Comment by jeandavidt** [comment]
I would suggest to use min and max to store:
* for parts with data type 'varchar' -> the min and max number of characters
* for units -> the physical limits for that unit. Otherwise, we would end up with what amounts to arbitrary limits (e.g., "Why can the sample temperature be 49C, but not 50C"?)
* Limits shouldn't be on the measures since measures can be expressed using various units, all of which will have their own bounds.

**Comment by DougManuel** [comment]
- For `varchar`, you would normally describe the max only. (zero is implied).
- Suggest that the data validation - type, max, min, etc. be for that part, not the value or category of that part - unless the part is a value or category. Meaning, I agree with @jeandavidt that for temp, the data validation is for the unit of temp. Not the actual temp part.

**Comment by mathew-thomson** [comment]
I think I follow - I'll implement it as outlined here then, resolving this issue.
