### ISSUE TITLE
Does this data model also store calibration curves.

### ISSUE THREAD

**Issue by hswerdfe** [Big-Life-Lab/PHES-ODM#28]
Got data today containing calibration curves do we store them and how?

**Comment by NielsNicolai** [comment]
One of the things I keep on repeating to myself is that this data model tries to bring the data of different labs & sites together with the goal of public health surveillence. Given this specific objective, the model already assumes that the data provided by the labs is sufficiently qualitative (i.e. the objective is not to do quality control for the labs). Following this reasoning, I would not include calibration curves/standard curves in this model (but note that the lab should internally be able to link a measurement point with a calibration curve, if required).

Is this reasoning correct?

**Comment by DougManuel** [comment]
Ideally, we would include templates that help generate data. A concern is that singleton data is collected earlier in the assay process with most other measures later in the assay process.

**Comment by NielsNicolai** [comment]
In Quebec we are thinking of logging 4 basic parameters of the calibration curves (intercept, slope, R2, efficiency of recovery) for each of the viral measurements (BRSV, PMMoV, SARS-CoV-2). How do we best integrate this in the current version of the data model?
@DougManuel @hswerdfe

**Comment by mathew-thomson** [comment]
Reviving this issue - I think that we could add the four measures that Niels mentions (intercept, slope, R2, efficiency of recovery) if we still think this may be important to capture. 

They would each just be added as a measure? I am tempted to say that they should be linked to a method, but since the method table shouldn't have to be updated every time, I think they are better captured as measures. 

Thoughts, @DougManuel @jeandavidt ?

**Comment by jeandavidt** [comment]
I agree that these items should be added for quality control. I think they would be measures and that they would be reported on lab control samples. I believe the fact that they are related to QA/QC would be captured by the `purposeID` field.
Do you agree @DougManuel ?
